import Footer from "./Components/Footer";
import NavBar from "./Components/Navbar";
import Topbar from "./Components/Topbar";

import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

export const metadata = {
  title: "Sawa Pharma (India) Pvt. Ltd.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
