
import Footer from "./Components/Footer";
import NavBar from "./Components/Navbar";
import TopStrip from "./Components/Topbar";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <TopStrip />
        <NavBar />
        {children}
     <Footer />
      </body>
    </html>
  );
}
